/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package br.com.bank

import br.com.bank.infra.DataConsumer
import br.com.bank.operation.consumer.OperationConsumer
import br.com.bank.operation.consumer.stdin.StdInDataConsumer
import br.com.bank.operation.consumer.stdin.StdInReader
import br.com.bank.operation.OperationEventConverter
import br.com.bank.operation.OperationResultOutput
import com.fasterxml.jackson.databind.DeserializationFeature
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.databind.SerializationFeature
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule
import com.fasterxml.jackson.module.kotlin.KotlinModule

class App {
    val greeting: String
        get() {
            return "Operations in a specific account!\nPress enter to stop input..."
        }
}

fun main(args: Array<String>) {
    println(App().greeting)
    val mapper = getCustomJacksonMapper()
    val operationConsumer =
            OperationConsumer(operationEventConverter = OperationEventConverter(mapper), reader = StdInReader())
    val dataConsumer: DataConsumer = StdInDataConsumer(operationConsumer = operationConsumer)

    dataConsumer.batchProcessing().forEach { println(mapper.writeValueAsString(OperationResultOutput.from(it))) }
}

private fun getCustomJacksonMapper(): ObjectMapper =
        ObjectMapper().registerModule(KotlinModule())
                .registerModule(JavaTimeModule())
//                .enable(SerializationFeature.WRAP_ROOT_VALUE)
                .enable(DeserializationFeature.UNWRAP_ROOT_VALUE)
                .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
